### ISSUE TITLE
Is it still alive?

### ISSUE THREAD

**Issue by QuinnFrederick** [JRHeaton/MIDIKit#2]
I've just been considering a large refactor of my apps' MIDI internal framework and came across this. You've done loads and I'd love to leverage it. Where are you at with the project?  I'd need to add my code to handle Bonjour discovery for iOS...

**Comment by JRHeaton** [comment]
The documentation is admittedly not in a good state. However, the framework functions and I use it to this day, without issues. I hope to put more effort into improving some parts of it soon, but cannot promise anything. I'm happy to answer any specific questions about it, and will attempt to fix any valid bugs for which issues are opened.

**Comment by JRHeaton** [comment]
Just for a public update, MIDIKit is undergoing a rewrite for Swift, and will no longer be ObjC-compatible or provide the JavaScriptCore layer. I mostly feel that the benefits of experimentation w/ JavaScript+midirepl are replaced with the ability to use this newer version (`swift` branch) with playgrounds.
